language: python
# command to install dependencies
#install:
#  - pip install . --use-mirrors
#  - pip install -r requirements.txt --use-mirrors
before_install:
  - gem install sass -v 3.2.18
  - gem install compass -v 0.12.2
  - gem install susy -v 1.0.9
  - gem install sassy-buttons -v 0.2.6
  - gem install bootstrap-sass -v 3.0.2.1
  - gem install compass-ui -v 0.0.5
  - npm install -g coffee-script
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - grunt
install:
  - python setup.py install
script:
  - python setup.py test
